1. Selection and filtering

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import pdfplumber

In [2]:
pdf_path="/home/paragchengappa/programming/UPI-Spending-Analyser/data/raw/bankstats.pdf"
text=""   # called an accumulator, stores all text

with pdfplumber.open(pdf_path) as pdf:
    for page in pdf.pages:
        page_text=page.extract_text()
        if page_text:
            text+=page_text+ "\n"         
print(text[:2000])

Transaction statement
9019517497, paragchengappa@gmail.com
Transactionstatementperiod Sent Received
01January2026-30June2026 ₹77,368.99 ₹70,536
Date&time Transactiondetails Amount
03Jan,2026 PaidtoJAYARAMAPB ₹30
07:41AM UPITransactionID:600358945338
PaidbyStateBankofIndia7202
03Jan,2026 PaidtoSHIVANNA SHIVANNA ₹231
02:17PM UPITransactionID:636962750553
PaidbyStateBankofIndia7202
05Jan,2026 PaidtoPARASHURAMA ₹56.15
07:29AM UPITransactionID:600553332781
PaidbyStateBankofIndia7202
05Jan,2026 PaidtoRAMESHMR ₹5
09:45AM UPITransactionID:600558105853
PaidbyStateBankofIndia7202
05Jan,2026 ReceivedfromMC NALINAKSHI ₹1,100
01:14PM UPITransactionID:969952655934
PaidtoStateBankofIndia7202
05Jan,2026 ReceivedfromMC NALINAKSHI ₹300
01:19PM UPITransactionID:527376183990
PaidtoStateBankofIndia7202
05Jan,2026 PaidtoBlinkit ₹1,112
01:19PM UPITransactionID:637121529011
PaidbyStateBankofIndia7202
06Jan,2026 PaidtoBMTCBUSKA57F1114 ₹15
12:03PM UPITransactionID:600608819250
PaidbyStateBankofIndia7202
Note:ThisstatementreflectspaymentsmadebyyouontheGooglePayapp.Selftransferpaymentsarenotincludedinthetotalmoneypaidand
received.AnypaymentstransactionsandactivitydeletedfromyourGoogleAccountwillnotshowupinthisstatement.
Page1of52
Transaction statement
9019517497, paragchengappa@gmail.com
Date&time Transactiondetails Amount
08Jan,2026 PaidtoSmartBazaar BengaluruFR47 ₹22.50
11:31AM UPITransactionID:600811739250
PaidbyStateBankofIndia7202
08Jan,2026 PaidtoKA01AR2969 ₹15
11:38AM UPITransactionID:600812237069
PaidbyStateBankofIndia7202
09Jan,2026 ReceivedfromMC NALINAKSHI ₹300
07:37AM UPITransactionID:648189265503
PaidtoStateBankofIndia7202
09Jan,2026 PaidtoMRAJESHWARIBAI ₹145
08:09AM UPITransactionID:600951222964
PaidbyStateBankofIndia7202
09Jan,2026 PaidtoSHAIK SALEEM ₹150
06:04PM UPITransactionID:637506446715
PaidbyStateBankofIndia7202
10Jan,2026 ReceivedfromMC NALINAKSHI ₹500
06:45AM UPITransactionID:310019683390
PaidtoStateBankofIndia7202
10Jan,2026 PaidtoSUDHAKAR CHITIKELA ₹173
07:28AM UPITra

In [3]:
transactions=[]

In [4]:
lines=text.splitlines()

In [5]:
print(lines)

['Transaction statement', '9019517497, paragchengappa@gmail.com', 'Transactionstatementperiod Sent Received', '01January2026-30June2026 ₹77,368.99 ₹70,536', 'Date&time Transactiondetails Amount', '03Jan,2026 PaidtoJAYARAMAPB ₹30', '07:41AM UPITransactionID:600358945338', 'PaidbyStateBankofIndia7202', '03Jan,2026 PaidtoSHIVANNA SHIVANNA ₹231', '02:17PM UPITransactionID:636962750553', 'PaidbyStateBankofIndia7202', '05Jan,2026 PaidtoPARASHURAMA ₹56.15', '07:29AM UPITransactionID:600553332781', 'PaidbyStateBankofIndia7202', '05Jan,2026 PaidtoRAMESHMR ₹5', '09:45AM UPITransactionID:600558105853', 'PaidbyStateBankofIndia7202', '05Jan,2026 ReceivedfromMC NALINAKSHI ₹1,100', '01:14PM UPITransactionID:969952655934', 'PaidtoStateBankofIndia7202', '05Jan,2026 ReceivedfromMC NALINAKSHI ₹300', '01:19PM UPITransactionID:527376183990', 'PaidtoStateBankofIndia7202', '05Jan,2026 PaidtoBlinkit ₹1,112', '01:19PM UPITransactionID:637121529011', 'PaidbyStateBankofIndia7202', '06Jan,2026 PaidtoBMTCBUSKA57F1114 ₹15', '12:03PM UPITransactionID:600608819250', 'PaidbyStateBankofIndia7202', 'Note:ThisstatementreflectspaymentsmadebyyouontheGooglePayapp.Selftransferpaymentsarenotincludedinthetotalmoneypaidand', 'received.AnypaymentstransactionsandactivitydeletedfromyourGoogleAccountwillnotshowupinthisstatement.', 'Page1of52', 'Transaction statement', '9019517497, paragchengappa@gmail.com', 'Date&time Transactiondetails Amount', '08Jan,2026 PaidtoSmartBazaar BengaluruFR47 ₹22.50', '11:31AM UPITransactionID:600811739250', 'PaidbyStateBankofIndia7202', '08Jan,2026 PaidtoKA01AR2969 ₹15', '11:38AM UPITransactionID:600812237069', 'PaidbyStateBankofIndia7202', '09Jan,2026 ReceivedfromMC NALINAKSHI ₹300', '07:37AM UPITransactionID:648189265503', 'PaidtoStateBankofIndia7202', '09Jan,2026 PaidtoMRAJESHWARIBAI ₹145', '08:09AM UPITransactionID:600951222964', 'PaidbyStateBankofIndia7202', '09Jan,2026 PaidtoSHAIK SALEEM ₹150', '06:04PM UPITransactionID:637506446715', 'PaidbyStateBankofIndia7202', '10Jan,2026 ReceivedfromMC NALINAKSHI ₹500', '06:45AM UPITransactionID:310019683390', 'PaidtoStateBankofIndia7202', '10Jan,2026 PaidtoSUDHAKAR CHITIKELA ₹173', '07:28AM UPITransactionID:601002394676', 'PaidbyStateBankofIndia7202', '10Jan,2026 PaidtoGANAGARAJA ₹159', '06:15PM UPITransactionID:601050762331', 'PaidbyStateBankofIndia7202', '10Jan,2026 ReceivedfromElwinEapenM ₹1,300', '06:56PM UPITransactionID:637648994552', 'PaidtoStateBankofIndia7202', '11Jan,2026 ReceivedfromMC NALINAKSHI ₹400', '08:38AM UPITransactionID:455604862043', 'PaidtoStateBankofIndia7202', 'Note:ThisstatementreflectspaymentsmadebyyouontheGooglePayapp.Selftransferpaymentsarenotincludedinthetotalmoneypaidand', 'received.AnypaymentstransactionsandactivitydeletedfromyourGoogleAccountwillnotshowupinthisstatement.', 'Page2of52', 'Transaction statement', '9019517497, paragchengappa@gmail.com', 'Date&time Transactiondetails Amount', '11Jan,2026 PaidtoElwinEapenM ₹1,300', '02:09PM UPITransactionID:637719244031', 'PaidbyStateBankofIndia7202', '12Jan,2026 PaidtoGOVINDAR ₹68', '07:27AM UPITransactionID:601293349335', 'PaidbyStateBankofIndia7202', '12Jan,2026 ReceivedfromAatreyoBhattacharya ₹34', '07:28AM UPITransactionID:601214100504', 'PaidtoStateBankofIndia7202', '12Jan,2026 PaidtoSADASHIVA ₹60', '09:46AM UPITransactionID:601299696879', 'PaidbyStateBankofIndia7202', '13Jan,2026 PaidtoVeeralChengappa ₹180', '05:00PM UPITransactionID:601389498644', 'PaidbyStateBankofIndia7202', '13Jan,2026 PaidtoZepto ₹172', '05:15PM UPITransactionID:601390983706', 'PaidbyStateBankofIndia7202', '14Jan,2026 PaidtoRANJANCSSOSHANKAREGOWDAT ₹66', '07:49AM UPITransactionID:601407006160', 'PaidbyStateBankofIndia7202', '14Jan,2026 PaidtoSmartBazaar BengaluruFR47 ₹33.84', '09:50AM UPITransactionID:601412984331', 'PaidbyStateBankofIndia7202', '14Jan,2026 PaidtoKA01AR2872 ₹15', '11:07AM UPITransactionID:601418439014', 'PaidbyStateBankofIndia7202', '14Jan,2026 ReceivedfromVeeralChengappa ₹50', '04:11PM UPITransactionID:601441537985', 'PaidtoStateBankofIndia7202', 'Note:ThisstatementreflectspaymentsmadebyyouontheGooglePayapp.Selftransferpaymentsarenotincludedinthetotalmoneypaidand', 'received.AnypaymentstransactionsandactivitydeletedfromyourGoogleAccountwillnotshowupinthisstatement.', 'Page3of52', 'Transaction statement', '9019517497, paragchengappa@gmail.com', 'Date&time Transactiondetails Amount', '14Jan,2026 PaidtoSwiggy ₹293', '04:11PM UPITransactionID:601441573813', 'PaidbyStateBankofIndia7202', '14Jan,2026 ReceivedfromMC NALINAKSHI ₹700', '07:50PM UPITransactionID:431100627561', 'PaidtoStateBankofIndia7202', '14Jan,2026 PaidtoZeptoMarketplacePrivateLimited ₹238', '07:51PM UPITransactionID:601416355997', 'PaidbyStateBankofIndia7202', '15Jan,2026 ReceivedfromVeeralChengappa ₹356', '06:09PM UPITransactionID:601507713180', 'PaidtoStateBankofIndia7202', '15Jan,2026 PaidtoZeptoMarketplacePrivateLimited ₹734', '06:10PM UPITransactionID:601507853714', 'PaidbyStateBankofIndia7202', '16Jan,2026 PaidtoRIDAFATHIMAKHANUM ₹62', '08:11AM UPITransactionID:601633095273', 'PaidbyStateBankofIndia7202', '16Jan,2026 PaidtoKA01AR1160 ₹15', '01:28PM UPITransactionID:601653745605', 'PaidbyStateBankofIndia7202', '16Jan,2026 ReceivedfromMC NALINAKSHI ₹300', '08:28PM UPITransactionID:040614333234', 'PaidtoStateBankofIndia7202', '16Jan,2026 PaidtoZEPTONOW ₹167', '08:29PM UPITransactionID:601678600375', 'PaidbyStateBankofIndia7202', '18Jan,2026 ReceivedfromMC NALINAKSHI ₹1,200', '03:23PM UPITransactionID:613372480269', 'PaidtoStateBankofIndia7202', 'Note:ThisstatementreflectspaymentsmadebyyouontheGooglePayapp.Selftransferpaymentsarenotincludedinthetotalmoneypaidand', 'received.AnypaymentstransactionsandactivitydeletedfromyourGoogleAccountwillnotshowupinthisstatement.', 'Page4of52', 'Transaction statement', '9019517497, paragchengappa@gmail.com', 'Date&time Transactiondetails Amount', '18Jan,2026 PaidtoZepto ₹901', '03:25PM UPITransactionID:601858105349', 'PaidbyStateBankofIndia7202', '19Jan,2026 PaidtoGREENTRENDS ₹418.95', '07:17PM UPITransactionID:601941366305', 'PaidbyStateBankofIndia7202', '19Jan,2026 PaidtoMSLIFECAREMEDICALS21 ₹10', '07:29PM UPITransactionID:601925661599', 'PaidbyStateBankofIndia7202', '21Jan,2026 PaidtoBMTCBUSKA57F2179 ₹15', '12:48PM UPITransactionID:602133924018', 'PaidbyStateBankofIndia7202', '21Jan,2026 ReceivedfromMC NALINAKSHI ₹1,000', '06:23PM UPITransactionID:914459556670', 'PaidtoStateBankofIndia7202', '21Jan,2026 ReceivedfromMC NALINAKSHI ₹350', '06:40PM UPITransactionID:864109874494', 'PaidtoStateBankofIndia7202', '21Jan,2026 PaidtoBlinkit ₹1,304', '07:20PM UPITransactionID:602102162743', 'PaidbyStateBankofIndia7202', '22Jan,2026 ReceivedfromMC NALINAKSHI ₹100', '08:00AM UPITransactionID:020308695444', 'PaidtoStateBankofIndia7202', '22Jan,2026 PaidtoSaniya Sultana ₹56', '08:12AM UPITransactionID:602229683035', 'PaidbyStateBankofIndia7202', '22Jan,2026 PaidtoRameshMR ₹5', '09:31AM UPITransactionID:602233734125', 'PaidbyStateBankofIndia7202', 'Note:ThisstatementreflectspaymentsmadebyyouontheGooglePayapp.Selftransferpaymentsarenotincludedinthetotalmoneypaidand', 'received.AnypaymentstransactionsandactivitydeletedfromyourGoogleAccountwillnotshowupinthisstatement.', 'Page5of52', 'Transaction statement', '9019517497, paragchengappa@gmail.com', 'Date&time Transactiondetails Amount', '23Jan,2026 ReceivedfromMC NALINAKSHI ₹500', '12:34PM UPITransactionID:633091135569', 'PaidtoStateBankofIndia7202', '23Jan,2026 PaidtoSoha ₹120', '12:37PM UPITransactionID:602301528217', 'PaidbyStateBankofIndia7202', '23Jan,2026 PaidtoMRSSARASWATHI GANESAN ₹100', '04:22PM UPITransactionID:602308703072', 'PaidbyStateBankofIndia7202', '23Jan,2026 PaidtoLipikaSridhar ₹22', '05:38PM UPITransactionID:602314961052', 'PaidbyStateBankofIndia7202', '23Jan,2026 PaidtoZEPTOMARKETPLACEPRIVATELIMITED ₹331', '05:48PM UPITransactionID:602315847545', 'PaidbyStateBankofIndia7202', '24Jan,2026 ReceivedfromVeeralChengappa ₹157', '10:42PM UPITransactionID:602493695505', 'PaidtoStateBankofIndia7202', '24Jan,2026 PaidtoZeptoMarketplacePrivateLimited ₹157', '10:43PM UPITransactionID:602493707171', 'PaidbyStateBankofIndia7202', '26Jan,2026 ReceivedfromMC NALINAKSHI ₹2,000', '10:01AM UPITransactionID:738225659382', 'PaidtoStateBankofIndia7202', '26Jan,2026 PaidtoZEPTOMARKETPLACEPRIVATELIMITED ₹1,524', '10:14AM UPITransactionID:602656486279', 'PaidbyStateBankofIndia7202', '26Jan,2026 ReceivedfromMC NALINAKSHI ₹500', '05:19PM UPITransactionID:409214704811', 'PaidtoStateBankofIndia7202', 'Note:ThisstatementreflectspaymentsmadebyyouontheGooglePayapp.Selftransferpaymentsarenotincludedinthetotalmoneypaidand', 'received.AnypaymentstransactionsandactivitydeletedfromyourGoogleAccountwillnotshowupinthisstatement.', 'Page6of52', 'Transaction statement', '9019517497, paragchengappa@gmail.com', 'Date&time Transactiondetails Amount', '27Jan,2026 PaidtoMANJUNATHAHN ₹82', '08:48AM UPITransactionID:602718410308', 'PaidbyStateBankofIndia7202', '27Jan,2026 PaidtoZEPTOMARKETPLACEPRIVATELIMITED ₹735', '01:22PM UPITransactionID:602736701603', 'PaidbyStateBankofIndia7202', '27Jan,2026 ReceivedfromMC NALINAKSHI ₹300', '05:51PM UPITransactionID:601609672685', 'PaidtoStateBankofIndia7202', '27Jan,2026 PaidtoBlinkit ₹216', '06:01PM UPITransactionID:602757391238', 'PaidbyStateBankofIndia7202', '28Jan,2026 PaidtoMRCHENNEGOWDA KC ₹59', '10:27AM UPITransactionID:602883419214', 'PaidbyStateBankofIndia7202', '28Jan,2026 PaidtoSSFOODANDBEVERAGE ₹10', '12:12PM UPITransactionID:602885523823', 'PaidbyStateBankofIndia7202', '28Jan,2026 PaidtoMRNishanthGowdaCM ₹30', '01:40PM UPITransactionID:602893095803', 'PaidbyStateBankofIndia7202', '28Jan,2026 ReceivedfromMC NALINAKSHI ₹600', '01:46PM UPITransactionID:429755875553', 'PaidtoStateBankofIndia7202', '28Jan,2026 PaidtoNAGARAJA ₹120', '01:51PM UPITransactionID:602893987952', 'PaidbyStateBankofIndia7202', '28Jan,2026 ReceivedfromMRNishanthGowdaCM ₹40', '01:52PM UPITransactionID:602830465081', 'PaidtoStateBankofIndia7202', 'Note:ThisstatementreflectspaymentsmadebyyouontheGooglePayapp.Selftransferpaymentsarenotincludedinthetotalmoneypaidand', 'received.AnypaymentstransactionsandactivitydeletedfromyourGoogleAccountwillnotshowupinthisstatement.', 'Page7of52', 'Transaction statement', '9019517497, paragchengappa@gmail.com', 'Date&time Transactiondetails Amount', '28Jan,2026 PaidtoZabeerAlikm ₹91', '06:00PM UPITransactionID:602812606632', 'PaidbyStateBankofIndia7202', '28Jan,2026 PaidtoNitikaAgarwal ₹32', '07:48PM UPITransactionID:602824071840', 'PaidbyStateBankofIndia7202', '29Jan,2026 PaidtoSWIGGY ₹156', '06:59AM UPITransactionID:602933397142', 'PaidbyStateBankofIndia7202', '29Jan,2026 PaidtoKISHANKUMAR ₹56', '08:00AM UPITransactionID:602934886075', 'PaidbyStateBankofIndia7202', '29Jan,2026 PaidtoBMTCBUSKA57F1114 ₹15', '12:23PM UPITransactionID:639568520087', 'PaidbyStateBankofIndia7202', '29Jan,2026 ReceivedfromMC NALINAKSHI ₹1,000', '08:18PM UPITransactionID:961513923829', 'PaidtoStateBankofIndia7202', '30Jan,2026 ReceivedfromMC NALINAKSHI ₹400', '06:02AM UPITransactionID:627110024346', 'PaidtoStateBankofIndia7202', '30Jan,2026 PaidtoZEPTOMARKETPLACEPRIVATELIMITED ₹399', '06:12AM UPITransactionID:117879767172', 'PaidbyStateBankofIndia7202', '30Jan,2026 PaidtoSWIGGY ₹132', '06:51AM UPITransactionID:639658884641', 'PaidbyStateBankofIndia7202', '30Jan,2026 PaidtoErannaHm ₹56', '08:01AM UPITransactionID:603078284649', 'PaidbyStateBankofIndia7202', 'Note:ThisstatementreflectspaymentsmadebyyouontheGooglePayapp.Selftransferpaymentsarenotincludedinthetotalmoneypaidand', 'received.AnypaymentstransactionsandactivitydeletedfromyourGoogleAccountwillnotshowupinthisstatement.', 'Page8of52', 'Transaction statement', '9019517497, paragchengappa@gmail.com', 'Date&time Transactiondetails Amount', '30Jan,2026 ReceivedfromAatreyoBhattacharya ₹15', '12:43PM UPITransactionID:117892568860', 'PaidtoStateBankofIndia7202', '30Jan,2026 PaidtoKA51AL6812 ₹6', '12:50PM UPITransactionID:603096414572', 'PaidbyStateBankofIndia7202', '30Jan,2026 PaidtoAatreyoBhattacharya ₹9', '12:56PM UPITransactionID:603096826887', 'PaidbyStateBankofIndia7202', '30Jan,2026 PaidtoZEPTOMARKETPLACEPRIVATELIMITED ₹224', '01:23PM UPITransactionID:603098890709', 'PaidbyStateBankofIndia7202', '30Jan,2026 ReceivedfromElwinEapenM ₹1,000', '07:09PM UPITransactionID:603020934047', 'PaidtoStateBankofIndia7202', '30Jan,2026 PaidtoElwinEapenM ₹1,000', '08:35PM UPITransactionID:603090816527', 'PaidbyStateBankofIndia7202', '31Jan,2026 PaidtoMAHENDRAHK ₹45', '09:36AM UPITransactionID:603154614733', 'PaidbyStateBankofIndia7202', '31Jan,2026 PaidtoRAMESHMR ₹3', '01:19PM UPITransactionID:603170693615', 'PaidbyStateBankofIndia7202', '31Jan,2026 PaidtoVENKATESHG ₹70', '02:05PM UPITransactionID:639721002506', 'PaidbyStateBankofIndia7202', '01Feb,2026 PaidtoZEPTOMARKETPLACEPRIVATELIMITED ₹255', '05:11PM UPITransactionID:603255408320', 'PaidbyStateBankofIndia7202', 'Note:ThisstatementreflectspaymentsmadebyyouontheGooglePayapp.Selftransferpaymentsarenotincludedinthetotalmoneypaidand', 'received.AnypaymentstransactionsandactivitydeletedfromyourGoogleAccountwillnotshowupinthisstatement.', 'Page9of52', 'Transaction statement', '9019517497, paragchengappa@gmail.com', 'Date&time Transactiondetails Amount', '01Feb,2026 ReceivedfromMC NALINAKSHI ₹300', '05:15PM UPITransactionID:743103723694', 'PaidtoStateBankofIndia7202', '02Feb,2026 PaidtoABHISHEKR ₹76', '08:40AM UPITransactionID:603379556105', 'PaidbyStateBankofIndia7202', '02Feb,2026 PaidtoSADASHIVA ₹60', '09:43AM UPITransactionID:603383398578', 'PaidbyStateBankofIndia7202', '02Feb,2026 PaidtoMr HARSHITH R ₹45', '02:11PM UPITransactionID:603304659167', 'PaidbyStateBankofIndia7202', '02Feb,2026 ReceivedfromMAbu ₹31', '02:57PM UPITransactionID:603308078887', 'PaidtoStateBankofIndia7202', '02Feb,2026 PaidtoKUMARA ₹55.59', '04:43PM UPITransactionID:603316095515', 'PaidbyStateBankofIndia7202', '02Feb,2026 PaidtoZEPTOMARKETPLACEPRIVATELIMITED ₹234.95', '09:08PM UPITransactionID:603343929105', 'PaidbyStateBankofIndia7202', '02Feb,2026 PaidtoSpotifyIndiaLIP ₹139', '10:10PM UPITransactionID:109114876136', 'PaidbyStateBankofIndia7202', '03Feb,2026 PaidtoMANIKANTAS ₹62', '07:57AM UPITransactionID:603455401093', 'PaidbyStateBankofIndia7202', '03Feb,2026 PaidtoManjunatha ₹46.45', '12:05PM UPITransactionID:603471757259', 'PaidbyStateBankofIndia7202', 'Note:ThisstatementreflectspaymentsmadebyyouontheGooglePayapp.Selftransferpaymentsarenotincludedinthetotalmoneypaidand', 'received.AnypaymentstransactionsandactivitydeletedfromyourGoogleAccountwillnotshowupinthisstatement.', 'Page10of52', 'Transaction statement', '9019517497, paragchengappa@gmail.com', 'Date&time Transactiondetails Amount', '04Feb,2026 ReceivedfromMC NALINAKSHI ₹700', '01:00PM UPITransactionID:311984377522', 'PaidtoStateBankofIndia7202', '04Feb,2026 PaidtoZEPTOMARKETPLACEPRIVATELIMITED ₹575', '01:01PM UPITransactionID:603551816054', 'PaidbyStateBankofIndia7202', '05Feb,2026 PaidtoVIGNESHVENKATESH ₹57.56', '07:51AM UPITransactionID:603605467844', 'PaidbyStateBankofIndia7202', '05Feb,2026 PaidtoLAFEMMEBEAUTYSALOON ₹200', '02:54PM UPITransactionID:640272542726', 'PaidbyStateBankofIndia7202', '05Feb,2026 PaidtoKavithaStores ₹10', '02:57PM UPITransactionID:603635398829', 'PaidbyStateBankofIndia7202', '05Feb,2026 ReceivedfromMC NALINAKSHI ₹500', '02:59PM UPITransactionID:451620863590', 'PaidtoStateBankofIndia7202', '05Feb,2026 PaidtoSYEDAFROZ ₹48.35', '03:21PM UPITransactionID:603637048676', 'PaidbyStateBankofIndia7202', '05Feb,2026 PaidtoChaiculture ₹120', '06:18PM UPITransactionID:603652080954', 'PaidbyStateBankofIndia7202', '05Feb,2026 ReceivedfromNitikaAgarwal ₹60', '06:19PM UPITransactionID:640285138973', 'PaidtoStateBankofIndia7202', '05Feb,2026 PaidtoMUSKAN ₹72', '06:57PM UPITransactionID:603656570142', 'PaidbyStateBankofIndia7202', 'Note:ThisstatementreflectspaymentsmadebyyouontheGooglePayapp.Selftransferpaymentsarenotincludedinthetotalmoneypaidand', 'received.AnypaymentstransactionsandactivitydeletedfromyourGoogleAccountwillnotshowupinthisstatement.', 'Page11of52', 'Transaction statement', '9019517497, paragchengappa@gmail.com', 'Date&time Transactiondetails Amount', '05Feb,2026 PaidtoZEPTOMARKETPLACEPRIVATELIMITED ₹233', '08:09PM UPITransactionID:603664655580', 'PaidbyStateBankofIndia7202', '05Feb,2026 ReceivedfromMC NALINAKSHI ₹310', '09:08PM UPITransactionID:157868726989', 'PaidtoStateBankofIndia7202', '06Feb,2026 PaidtoS APPU ₹60', '07:35AM UPITransactionID:603779895923', 'PaidbyStateBankofIndia7202', '06Feb,2026 PaidtoSADASHIVA ₹60', '09:49AM UPITransactionID:603786739176', 'PaidbyStateBankofIndia7202', '06Feb,2026 PaidtoABHISHEKSHANKINAMATH ₹69', '03:24PM UPITransactionID:603711957820', 'PaidbyStateBankofIndia7202', '07Feb,2026 PaidtoBundlTechnologiespvtLtd ₹214', '06:55AM UPITransactionID:603810479296', 'PaidbyStateBankofIndia7202', '07Feb,2026 ReceivedfromMC NALINAKSHI ₹300', '08:12AM UPITransactionID:081674348346', 'PaidtoStateBankofIndia7202', '07Feb,2026 PaidtoChandrashekharGowda ₹56', '08:12AM UPITransactionID:603839867993', 'PaidbyStateBankofIndia7202', '07Feb,2026 PaidtoChaiculture ₹120', '01:19PM UPITransactionID:603860190715', 'PaidbyStateBankofIndia7202', '07Feb,2026 ReceivedfromAamenaHussain ₹60', '01:19PM UPITransactionID:603822095745', 'PaidtoStateBankofIndia7202', 'Note:ThisstatementreflectspaymentsmadebyyouontheGooglePayapp.Selftransferpaymentsarenotincludedinthetotalmoneypaidand', 'received.AnypaymentstransactionsandactivitydeletedfromyourGoogleAccountwillnotshowupinthisstatement.', 'Page12of52', 'Transaction statement', '9019517497, paragchengappa@gmail.com', 'Date&time Transactiondetails Amount', '07Feb,2026 PaidtoKA01AR1160 ₹15', '01:33PM UPITransactionID:603861454077', 'PaidbyStateBankofIndia7202', '08Feb,2026 PaidtoZEPTOMARKETPLACEPRIVATELIMITED ₹1,089.95', '11:27AM UPITransactionID:640581693176', 'PaidbyStateBankofIndia7202', '09Feb,2026 PaidtoErannaHm ₹65', '08:05AM UPITransactionID:604031409110', 'PaidbyStateBankofIndia7202', '10Feb,2026 ReceivedfromMC NALINAKSHI ₹400', '06:30AM UPITransactionID:288382747217', 'PaidtoStateBankofIndia7202', '10Feb,2026 PaidtoSwiggyLimited ₹167', '07:21AM UPITransactionID:640746597945', 'PaidbyStateBankofIndia7202', '10Feb,2026 PaidtoCHARLESARUNKUMAR ₹65', '08:01AM UPITransactionID:604164366630', 'PaidbyStateBankofIndia7202', '10Feb,2026 PaidtoRUDRESHMT ₹50', '01:17PM UPITransactionID:604199631975', 'PaidbyStateBankofIndia7202', '10Feb,2026 ReceivedfromMC NALINAKSHI ₹300', '01:25PM UPITransactionID:642792870280', 'PaidtoStateBankofIndia7202', '10Feb,2026 PaidtoZEPTOMARKETPLACEPRIVATELIMITED ₹181', '01:25PM UPITransactionID:604156529492', 'PaidbyStateBankofIndia7202', '11Feb,2026 PaidtoZABIULLAMM ₹56', '08:00AM UPITransactionID:640841213608', 'PaidbyStateBankofIndia7202', 'Note:ThisstatementreflectspaymentsmadebyyouontheGooglePayapp.Selftransferpaymentsarenotincludedinthetotalmoneypaidand', 'received.AnypaymentstransactionsandactivitydeletedfromyourGoogleAccountwillnotshowupinthisstatement.', 'Page13of52', 'Transaction statement', '9019517497, paragchengappa@gmail.com', 'Date&time Transactiondetails Amount', '11Feb,2026 PaidtoUNICORNENTERPRISE ₹99', '12:32PM UPITransactionID:604234165594', 'PaidbyStateBankofIndia7202', '11Feb,2026 PaidtoSuriNayak ₹48.86', '02:29PM UPITransactionID:640870554047', 'PaidbyStateBankofIndia7202', '12Feb,2026 ReceivedfromMC NALINAKSHI ₹500', '06:11AM UPITransactionID:115379936365', 'PaidtoStateBankofIndia7202', '12Feb,2026 PaidtoBundlTechnologiespvtLtd ₹214', '10:42AM UPITransactionID:604373986404', 'PaidbyStateBankofIndia7202', '12Feb,2026 PaidtoZEPTOMARKETPLACEPRIVATELIMITED ₹277', '10:50AM UPITransactionID:640971134236', 'PaidbyStateBankofIndia7202', '13Feb,2026 PaidtoARUNKUMARN ₹56', '07:50AM UPITransactionID:604412008032', 'PaidbyStateBankofIndia7202', '13Feb,2026 ReceivedfromMC NALINAKSHI ₹300', '11:03AM UPITransactionID:024514047167', 'PaidtoStateBankofIndia7202', '13Feb,2026 PaidtoRAMESHMR ₹45', '01:25PM UPITransactionID:604433551948', 'PaidbyStat

In [6]:
import re
i=0

while i<len(lines):
    line=lines[i]

    if re.match(r"\d{2}[A-Za-z]{3,9},\d{4}",line):
        line1=lines[i]
        line2=lines[i+1]
        line3=lines[i+2]

        date=re.search(r"\d{2}[A-Za-z]{3,9},\d{4}",line1).group()

        amount=re.search(r"₹[\d,\.]+",line1).group()

        details=line1.replace(date,"")             #details=string after replacing date w "" from line1
        details=details.replace(amount,"").strip() #details=replace amount from DETAILS w ""
                                                   #strip blank spaces "","" which replaced date and amount
                                                   #and then assign to details

        time=re.search(r"\d{2}:\d{2}[AP]M",line2).group()

        upi=re.search(r"\d{12}",line2).group()
        bank=line3                                 # since in text, third line of each transaction is Paidby/toStateBankOfIndia

        transactions.append([date,time,details,amount,upi,bank])
        i+=3
    else:
        i+=1

In [7]:
df=pd.DataFrame(transactions,columns=["Date","Time","Details","Amount","UPI_ID","Bank"])
df.head()

,Date,Time,Details,Amount,UPI_ID,Bank
0,"03Jan,2026",07:41AM,PaidtoJAYARAMAPB,₹30,600358945338,PaidbyStateBankofIndia7202
1,"03Jan,2026",02:17PM,PaidtoSHIVANNA SHIVANNA,₹231,636962750553,PaidbyStateBankofIndia7202
2,"05Jan,2026",07:29AM,PaidtoPARASHURAMA,₹56.15,600553332781,PaidbyStateBankofIndia7202
3,"05Jan,2026",09:45AM,PaidtoRAMESHMR,₹5,600558105853,PaidbyStateBankofIndia7202
4,"05Jan,2026",01:14PM,ReceivedfromMC NALINAKSHI,"₹1,100",969952655934,PaidtoStateBankofIndia7202

In [8]:
df["Date"]=pd.to_datetime(df["Date"],format= "%d%b,%Y")
df["Amount"]=(df["Amount"].str.replace("₹","",regex=False)
              .str.replace(",","",regex=False))
df["Amount"]=df["Amount"].astype(float)
df.info
df.isnull().sum()
df.duplicated().sum()

0

In [9]:
print(df["Details"])

0               PaidtoJAYARAMAPB
1        PaidtoSHIVANNA SHIVANNA
2              PaidtoPARASHURAMA
3                 PaidtoRAMESHMR
4      ReceivedfromMC NALINAKSHI
                 ...
508            PaidtoAmazonIndia
509    ReceivedfromMC NALINAKSHI
510                 PaidtoMyntra
511    ReceivedfromMC NALINAKSHI
512                PaidtoBlinkit
Name: Details, Length: 513, dtype: object

In [10]:
df["Transaction_Type"]=df["Details"].str.contains(r"Paid",case=False, na=False).map({True:"Paid",
                                                                                     False:"Received"
                                                                                    })

In [11]:
#DEL
print(df["Transaction_Type"])

0          Paid
1          Paid
2          Paid
3          Paid
4      Received
         ...
508        Paid
509    Received
510        Paid
511    Received
512        Paid
Name: Transaction_Type, Length: 513, dtype: object

In [12]:
df["Merchant"]= df["Details"].str.replace("Paidto","",regex=False).str.replace("Receivedfrom","",regex=False).str.strip().str.title()
print(df["Merchant"])

0             Jayaramapb
1      Shivanna Shivanna
2            Parashurama
3               Rameshmr
4          Mc Nalinakshi
             ...
508          Amazonindia
509        Mc Nalinakshi
510               Myntra
511        Mc Nalinakshi
512              Blinkit
Name: Merchant, Length: 513, dtype: object

In [13]:
df["Day"]=df["Date"].dt.day
df["Day_Name"]=df["Date"].dt.day_name()
df["Month"]=df["Date"].dt.month_name()
df["Year"]=df["Date"].dt.year

In [14]:
df["Bank"]=(df["Bank"].str.replace("Paidto","",regex=False).str.replace("Paidby","",regex=False).str.strip())

In [15]:
df.head()

,Date,Time,Details,Amount,UPI_ID,Bank,Transaction_Type,Merchant,Day,Day_Name,Month,Year
0,2026-01-03,07:41AM,PaidtoJAYARAMAPB,30.00,600358945338,StateBankofIndia7202,Paid,Jayaramapb,3,Saturday,January,2026
1,2026-01-03,02:17PM,PaidtoSHIVANNA SHIVANNA,231.00,636962750553,StateBankofIndia7202,Paid,Shivanna Shivanna,3,Saturday,January,2026
2,2026-01-05,07:29AM,PaidtoPARASHURAMA,56.15,600553332781,StateBankofIndia7202,Paid,Parashurama,5,Monday,January,2026
3,2026-01-05,09:45AM,PaidtoRAMESHMR,5.00,600558105853,StateBankofIndia7202,Paid,Rameshmr,5,Monday,January,2026
4,2026-01-05,01:14PM,ReceivedfromMC NALINAKSHI,1100.00,969952655934,StateBankofIndia7202,Received,Mc Nalinakshi,5,Monday,January,2026

In [16]:
print(df["Merchant"].unique())

['Jayaramapb' 'Shivanna Shivanna' 'Parashurama' 'Rameshmr' 'Mc Nalinakshi'
 'Blinkit' 'Bmtcbuska57F1114' 'Smartbazaar Bengalurufr47' 'Ka01Ar2969'
 'Mrajeshwaribai' 'Shaik Saleem' 'Sudhakar Chitikela' 'Ganagaraja'
 'Elwineapenm' 'Govindar' 'Aatreyobhattacharya' 'Sadashiva'
 'Veeralchengappa' 'Zepto' 'Ranjancssoshankaregowdat' 'Ka01Ar2872'
 'Swiggy' 'Zeptomarketplaceprivatelimited' 'Ridafathimakhanum'
 'Ka01Ar1160' 'Zeptonow' 'Greentrends' 'Mslifecaremedicals21'
 'Bmtcbuska57F2179' 'Saniya Sultana' 'Soha' 'Mrssaraswathi Ganesan'
 'Lipikasridhar' 'Manjunathahn' 'Mrchennegowda Kc' 'Ssfoodandbeverage'
 'Mrnishanthgowdacm' 'Nagaraja' 'Zabeeralikm' 'Nitikaagarwal'
 'Kishankumar' 'Erannahm' 'Ka51Al6812' 'Mahendrahk' 'Venkateshg'
 'Abhishekr' 'Mr Harshith R' 'Mabu' 'Kumara' 'Spotifyindialip'
 'Manikantas' 'Manjunatha' 'Vigneshvenkatesh' 'Lafemmebeautysaloon'
 'Kavithastores' 'Syedafroz' 'Chaiculture' 'Muskan' 'S Appu'
 'Abhishekshankinamath' 'Bundltechnologiespvtltd' 'Chandrashekhargowda'
 'Aamenahussain' 'Swiggylimited' 'Charlesarunkumar' 'Rudreshmt'
 'Zabiullamm' 'Unicornenterprise' 'Surinayak' 'Arunkumarn' 'Swarabakes'
 'Sunithabs' 'Anilkumar' 'Harishsn' 'Arunkumar' 'Nykaa' 'Myntra'
 'Rvakashgowda' 'Khushichatscenter' 'Fadiamansaifudeen' 'Afnaazmujawar'
 'Justvendprivatelimited' 'Avarshithsai' 'Mrhanumantha' 'Stameemulansari'
 'Ajaiantonyjoseph' 'Mrchikkeregowda Xx' 'Zameer Pasha' 'Faisalnowshad'
 'Puneriamruttulyasairamcafe' 'Mventerprises' 'Shahidulalam'
 'Mahanthesh R W00616' 'Swastikasengupta' 'Montusharma'
 'Houseofcommonshouseofcommonsjpnagar' 'Dhruva Kumar' 'Kumart'
 'Elwineapen' 'Rjaipal' 'Karnatakastateroadtransportcorporation'
 'Aryanbhushan' 'Ganesh' 'Sakaleshkg' 'Srikrishnacafe' 'Puneethkn'
 'Reshmaps' 'Harishkumardr' 'Bmrclbtmlayout' 'Bmrclchpktom0004'
 'Prashanthprashanth' 'Ruchitajain' 'Janardhanav' 'Harisha'
 'Kvenkataswamy' 'Shankarahm' 'Zeptomarketplacepr' 'Hajeerabanu' 'J Rajni'
 'Bmrclindiranagar' 'Sachins' 'Dhillonthimmaiahcb' 'Googleplay'
 'Prasannakumarbd' 'Mohankumarn' 'Mahadevakm' 'Nandan A' 'Swiggyinstamart'
 'Jioprepaid' 'Manoj' 'Anandkoushi' 'Jayantha' 'Sampatha' 'Rajeshv'
 'Pavanpavan' 'Ramya Hc' 'Rpradeepbhonsle' 'Subramanin' 'Mogalnayabrasool'
 'Praveenkumarpandi' 'Kumarm' 'Muhibullakhanj' 'Mrvmohan'
 'Naveedcondiments' 'Khshoukathali' 'Yeshodharankp'
 'Anithamedicalsandgeneralstores' 'Rupeshkumark' 'Ka01Ar4375' 'Sureshats'
 'Rmuniraju' 'Manjegowdane' 'Ka01Ar2824' 'Farmerskart'
 'Maheshnarasimhaamb' 'Santhoshkumar' 'Namanm' 'Sherenemariamathews'
 'Zomato' 'Tabrez' 'Afrozepashak' 'Venkivenki' 'Nalinichengappa'
 'Shruthi S' 'Guruswamydesavallishankarraju' 'Ashirwadsupermarkethd'
 'Kumar C' 'Sadashivaiah' 'Preplacededucationprivatelimited' 'Razorpay'
 'Satishn' 'Vajrappap' 'Shankar M' 'Bmtcbuska57F0010'
 'Nagappashamtappaalagud' 'Mrramesh' 'Blinkitcommerceprivatelimited'
 'Prashanth' 'Harishstore' 'Armugamvijay' 'Charlesh' 'Shamikhabanu'
 'Prakasha V' 'Vijaya Kumar' 'Saravanasosrinivasa' 'Vignesh V' 'Bmtc'
 'Jrakashsoravi' 'Bmtcbuska57F1045' 'Deepu' 'Shivalingegowdadc' 'Vigneshm'
 'Balajistationers' 'Shivanna S' 'Vishal' 'Sameerr' 'Snsnsnnssnnw'
 'Shivamjpatel' 'Krishnamurthysj' 'Lalrinomi Ngamlai'
 'Edenfreshfruitsandvegetables' 'Vinodkumarr' 'Shekarm' 'Ka01Ar2809'
 'Mularam' 'Prakash Rao' 'Mrharoonrasheed' 'Praveen' 'Mohammedthowfeeq'
 'Viswanathan G' 'Amazonindia' 'Madhur' 'Nayazkhan' 'Anandamanjegowda'
 'Dharmarajmn' 'Kayaliramanappa' 'Sunilrajr' 'Irfan Vali' 'Thecoral'
 'Jiohotstar' 'Getgorgeous' 'Aarnamedicals' 'More' 'Nishanradesh'
 'Coorgavenuesuperstore' 'Smartpartsonline']

- MERCHANT NORMALIZATION

In [17]:
merchant_categorization={
            "Groceries":{
                    "Blinkit":[r"blinkit"],
                    "Swiggy Instamart":[r"swiggy\s*instamart|instamart"],
                    "Zepto":[r"zepto"]
                    },
            "Transport":{
                    "Transport":[r"Ka0|Bmtc|Bmrcl"]
                    },
            "Food":{
                    r"restaurant|chai|coffee|tea|cafe|resto|bar"
                    "Swiggy":[r"swiggy|bundl"],
                    "Zomato":[r"Zomato"],
                    "Ownly":[r"Ownly"]
            },
}

In [18]:
df["Merchant"]=df["Merchant"].str.isinstance(merchant_categorization)

AttributeError: 'StringMethods' object has no attribute 'isinstance'

In [2]:
# Run this inside a Jupyter Notebook cell to retrieve your executed code history
for i, code in enumerate(In):
    if code.strip():
        print(f"--- [CELL {i}] ---")
        print(code)
        print("\n")

--- [CELL 1] ---
# Run this inside a Jupyter Notebook cell (NOT in a terminal .py script)
for i, code in enumerate(In):
    if code.strip():
        print(f"--- [CELL {i}] ---")
        print(code)
        print("\n")


--- [CELL 2] ---
# Run this inside a Jupyter Notebook cell to retrieve your executed code history
for i, code in enumerate(In):
    if code.strip():
        print(f"--- [CELL {i}] ---")
        print(code)
        print("\n")